
-- NOTE: I didn't write this script myself, it was exported from MySQL Workbench. The model file is also included in the docs.

-- MySQL Script generated by MySQL Workbench
-- Thu Dec  8 18:44:21 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema wheel_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema wheel_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wheel_db` DEFAULT CHARACTER SET utf8 ;
USE `wheel_db` ;

-- -----------------------------------------------------
-- Table `wheel_db`.`lobby`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wheel_db`.`lobby` ;

CREATE TABLE IF NOT EXISTS `wheel_db`.`lobby` (
  `lobbyID` INT NOT NULL AUTO_INCREMENT,
  `accessCode` VARCHAR(8) NOT NULL,
  `timerStart` INT NULL,
  PRIMARY KEY (`lobbyID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wheel_db`.`player`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wheel_db`.`player` ;

CREATE TABLE IF NOT EXISTS `wheel_db`.`player` (
  `playerID` INT NOT NULL AUTO_INCREMENT,
  `lobbyID` INT NOT NULL,
  `playerName` VARCHAR(45) NOT NULL,
  `isReady` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`playerID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wheel_db`.`prompt`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wheel_db`.`prompt` ;

CREATE TABLE IF NOT EXISTS `wheel_db`.`prompt` (
  `promptID` INT NOT NULL AUTO_INCREMENT,
  `lobbyID` INT NOT NULL,
  `playerID` INT NULL,
  `prompt` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`promptID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
